direction: down

hub: Hub VPC {
  prj: prj-hub {
    vpn: Cloud VPN {
      shape: image
      icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FNetworking%2FCloud%20VPN.svg
    }

    nat: Cloud NAT {
      shape: image
      icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FNetworking%2FCloud%20NAT.svg
    }
  }
}

spk1: Spoke 1 VPC {
  prj: prj-spoke-01 {
    sub1: "us-west1 | 10.0.1.0/24"

    nat: Cloud NAT {
      shape: image
      icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FNetworking%2FCloud%20NAT.svg
    }
  }

  svcs: Service projects
}

spk2: Spoke 2 VPC {
  prj: prj-spoke-01 {
    sub1: "us-west1 | 10.0.2.0/24"
    sub2: "us-central1 | 10.0.3.0/24"

    nat: Cloud NAT {
      shape: image
      icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FNetworking%2FCloud%20NAT.svg
    }
  }

  svcs: Service projects
}

hub <-> spk1: VPC Peering
hub <-> spk2: VPC Peering

spk1.prj <- spk1.svcs: Shared VPC {
  style {
    stroke-dash: 3
  }
}
spk2.prj <- spk2.svcs: Shared VPC {
  style {
    stroke-dash: 3
  }
}

spk1.svcs.style.multiple: true
spk2.svcs.style.multiple: true

# explanation: |md
#   ### Why do we use AWS?
#   - It has more uptime than GCloud
#   - We have free credits
# | {
#   near: hub
# }

title: |md
  # Hub and Spoke Architecture
| {near: top-center}
